m1=matrix(1:20,nrow=5,ncol = 4)
print("5*4 Matrix")
print(m1)
cells=c(1,3,5,7,8,9,11,12,13)
rnames=c("R1","R2","R3")
cnames=c("C1","C2","C3")
m2=matrix(cells,nrow=3,ncol=3,byrow = TRUE,dimnames = list(rnames,cnames))
print("the matrix filled with rows")
print(m2)
print("Matrix filled with columns")
m3=matrix(cells,nrow=3,ncol=3,byrow = FALSE,dimnames = list(rnames,cnames))
print(m3)
